- hosts: localhost
  tasks:
  - name: Deploy the server
    k8s:
      state: present
      definition: "{{ lookup('template', 'statefulset.yaml') | from_yaml }}"
      validate_certs: no
      namespace: default
