apiVersion: v1
kind: PersistentVolume
metadata:
  name: group-pv
  labels:
    vol: nginx
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/app"

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: group-pvc
  labels:
    vol: nginx
spec:
  accessModes: 
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
  selector:
    matchLabels:
      vol: nginx

apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: group
spec:
  serviceName: nginx
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: httpd
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: nginx-vol
          mountPath: /usr/share/nginx/html
      volumes:
      - name: nginx-vol
        persistentVolumeClaim:
          claimName: group-pvc
